server:
  port: 8080
  servlet:
    context-path: /financialplanning

spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=FinancialPlanning;trustServerCertificate=true;encrypt=true"
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 4lJpj@example.com
    password: 123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true