IF EXISTS (SELECT NAME FROM MASTER.DBO.SYSDATABASES WHERE NAME = N'FinancialPlanning')
    BEGIN
        DROP DATABASE [FinancialPlanning]
    END

CREATE DATABASE FinancialPlanning
GO
USE FinancialPlanning
GO

-- ACCOUNT Table
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY IDENTITY(1,1),
    USER_NAME NVARCHAR(50) NOT NULL UNIQUE,
    FULL_NAME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL UNIQUE,
    PASSWORD NVARCHAR(255) NOT NULL,
    PHONE_NUMBER NVARCHAR(20) NOT NULL UNIQUE,
    DOB DATE NOT NULL,
    ADDRESS NVARCHAR(255),
    DEPARTMENT_ID INT NOT NULL,
    POSITION_ID INT NOT NULL,
    ROLE INT NOT NULL,
    USER_STATUS INT DEFAULT 1,
    NOTE NVARCHAR(255),
    CREATE_ID INT,
    UPDATE_ID INT,
    CREATE_DATE_TIME DATETIME DEFAULT GETDATE(),
    UPDATE_DATE_TIME DATETIME,
    DELETE_FLAG BIT DEFAULT 0
);

-- TERM Table
CREATE TABLE TERM (
    TERM_ID NVARCHAR(20) PRIMARY KEY,
    TERM_NAME NVARCHAR(255) NOT NULL,
    DURATION INT,
    START_DATE DATE NOT NULL,
    PLAN_DUE_DATE DATE NOT NULL,
    REPORT_DUE_DATE DATE NOT NULL,
    TERM_STATUS INT DEFAULT 1,
    CREATE_ID INT,
    UPDATE_ID INT,
    CREATE_DATE_TIME DATETIME DEFAULT GETDATE(),
    UPDATE_DATE_TIME DATETIME,
    DELETE_FLAG BIT DEFAULT 0
);

-- PLAN Table
CREATE TABLE [PLAN] (
    PLAN_ID NVARCHAR(20) PRIMARY KEY,
    TERM_ID NVARCHAR(20) NOT NULL,
    PLAN_NAME NVARCHAR(255) NOT NULL,
    DEPARTMENT_ID INT,
    PLAN_STATUS INT DEFAULT 1,
    VERSION INT DEFAULT 1,
    CREATE_ID INT,
    UPDATE_ID INT,
    CREATE_DATE_TIME DATETIME DEFAULT GETDATE(),
    UPDATE_DATE_TIME DATETIME,
    DELETE_FLAG BIT DEFAULT 0,
    FOREIGN KEY (TERM_ID) REFERENCES TERM(TERM_ID)
);

-- PLAN_DETAIL Table
CREATE TABLE PLAN_DETAIL (
    PLAN_DETAIL_ID NVARCHAR(20) UNIQUE NOT NULL,
    PLAN_ID NVARCHAR(20) NOT NULL,
    EXPENSE NVARCHAR(255),
    COST_TYPE INT,
    UNIT_PRICE DECIMAL(18,0),
    AMOUNT INT,
    PROJECT_NAME NVARCHAR(100),
    SUPPLIER_NAME NVARCHAR(100),
    PIC NVARCHAR(50),
    NOTE NVARCHAR(255),
    EXPENSE_STATUS INT DEFAULT 1,
    PRIMARY KEY (PLAN_DETAIL_ID, PLAN_ID),
    FOREIGN KEY (PLAN_ID) REFERENCES [PLAN](PLAN_ID)
);


-- MONTH_REPORT Table
CREATE TABLE MONTH_REPORT (
    MONTH_REPORT_ID NVARCHAR(20) PRIMARY KEY,
    TERM_ID NVARCHAR(20) NOT NULL,
	MONTH_REPORT_NAME NVARCHAR(255),
    MONTH DATE,
    DEPARTMENT_ID INT,
    REPORT_STATUS INT,
    VERSION INT DEFAULT 1,
    CREATE_ID INT,
    UPDATE_ID INT,
    CREATE_DATE_TIME DATETIME DEFAULT GETDATE(),
    UPDATE_DATE_TIME DATETIME,
    DELETE_FLAG BIT DEFAULT 0,
    FOREIGN KEY (TERM_ID) REFERENCES TERM(TERM_ID)
);

-- MONTH_REPORT_DETAIL Table
CREATE TABLE MONTH_REPORT_DETAIL (
    MONTH_REPORT_DETAIL_ID NVARCHAR(20) UNIQUE NOT NULL,
    MONTH_REPORT_ID NVARCHAR(20) NOT NULL,
    EXPENSE NVARCHAR(255),
    COST_TYPE INT,
    UNIT_PRICE DECIMAL(18,0),
    AMOUNT INT,
    PROJECT_NAME NVARCHAR(100),
    SUPPLIER_NAME NVARCHAR(100),
    PIC NVARCHAR(50),
    NOTE NVARCHAR(255),
    PRIMARY KEY (MONTH_REPORT_DETAIL_ID, MONTH_REPORT_ID),
    FOREIGN KEY (MONTH_REPORT_ID) REFERENCES MONTH_REPORT(MONTH_REPORT_ID)
);

-- MASTER Table
CREATE TABLE MASTER (
    M_CODE INT NOT NULL,
    M_ID INT NOT NULL,
    VALUE NVARCHAR(255),
    PRIMARY KEY (M_CODE, M_ID)
);

-- Insert initial data into MASTER table
INSERT INTO MASTER (M_CODE, M_ID, VALUE)
VALUES
    (1, 1, 'Admin'),
    (1, 2, 'Accountant'),
    (1, 3, 'Financial staff'),
    (2, 1, 'IT'),
    (2, 2, 'HR'),
    (2, 3, 'Finance'),
    (2, 4, 'Communication'),
    (2, 5, 'Marketing'),
    (2, 6, 'Accounting'),
    (3, 1, 'Financial Executive'),
    (3, 2, 'Project manager'),
    (3, 3, 'Office Assistant'),
    (3, 4, 'Senior Executive'),
    (3, 5, 'Accounting Executive'),
    (3, 6, 'Junior Executive'),
    (3, 7, 'Intern'),
    (4, 1, 'Direct Costs'),
    (4, 2, 'Indirect Costs'),
    (4, 3, 'Administration Costs'),
    (4, 4, 'Operating Costs'),
    (4, 5, 'Maintenance Costs'),
    (4, 6, 'Manufacturing Costs'),
    (5, 1, 'Active'),
    (5, 2, 'Inactive'),
    (6, 1, 'Monthly'),
    (6, 3, 'Quarterly'),
    (6, 6, 'Half-year'),
    (7, 1, 'New'),
    (7, 2, 'In-Progress'),
    (7, 3, 'Closed'),
    (8, 1, 'New'),
    (8, 2, 'Waiting for Approval'),
    (8, 3, 'Approved'),
    (8, 4, 'Denied'),
    (8, 5, 'Closed'),
    (9, 1, 'New'),
    (9, 2, 'Closed'),
	(10, 1, 'Quarter 1'),
    (10, 2, 'Quarter 2'),
    (10, 3, 'Quarter 3'),
    (10, 4, 'Quarter 4');

